### ISSUE TITLE
Too many event listeners

### ISSUE THREAD

**Issue by serkanatpaystack** [ooade/raap#4]
It feels to me that creating an event listener per menu item may not be very scalable as the menu grows

https://github.com/ooade/raap/blob/8c3b5c0ca6662b22e491034d2fca0949c5254f33/index.js#L8

Is there a way to create one event listener to achieve the same result?

**Comment by serkanatpaystack** [comment]
This is a question, you do not need to code it again, and are welcome to provide a response here.

**Comment by ooade** [comment]
@serkanatpaystack Okay. There's one way to do it. Add an event listener to the body and match the classNames to the specific menuItems. Once a match is found, add or remove classList.

**Comment by serkanatpaystack** [comment]
Sounds like a solution towards a workable direction. Thank you.
